<?_head("Quotes")?>

<ul>
<li> If the human brain were so simple that we could understand it, we would be so simple we couldn't.  
<li> A hacker does for love what others would not do for money.
<li> Access denied--nah nah na nah nah!
<li> As a computer, I find your faith in technology amusing.
<li> Computers are useless. They can only give you answers. - <i>Picasso</i>
<li> Help! I'm trapped in a Chinese computer factory!
<li> We know Linux is the best, it can do infinitie loops in five seconds. - <i>Linus Torvalds</i>
<li> Thou shalt not follow the NULL pointer for chaos and madness await thee at its end.
<li> Yesterday upon the stair<br>
     I met a man who wasn't there.<br>
     He wasn't there again today --<br>
     I think he's from the CIA.
<li> Give a man a fish and he will eat for a day, but teach a man to fish and he will eat for eternity.
<li> Friends don't let friends use DOS.
<li> One who has time to complain has time to submit patches. - chinese proverb
<li> Life is complex: it has real and imaginary parts.
<li> Some things seem like bugs, but it's just ignorance... cal 9 1752
<li> Veel denken, niet veel weten moet je nastreven. - <i>Democritus</i>
<li> Boards don't hit back. - <i>Bruce Lee</i>
<li> PS: Unix was not designed to prevent you from doing stupid things...
<li> When she told me I was average, she was just being mean.
<li> It is better to keep your mouth shut and be thought a fool, than to open it and remove all doubt.
<li> There is no such thing as luck. 'Luck' is nothing but an absence of bad luck.
<li>I want to die peacefully in my sleep as my grandfather did,<br>
    unlike the passengers in his car.
<li> "I have no respect for a man who can only spell a word one way." - Mark Twain
<li> "Your work is both true and original. Unfortunately, the parts that are true are not original, and the parts that are original are not true." -- Edgar Allan Poe
<li> "I have never let my schooling interfere with my education." -- Mark Twain
<li> "Few things are harder to put up with than a good example." -- Mark Twain 
<li> "When in doubt tell the truth." --  Mark Twain
<li> "Friends are those rare people who ask how we are and then wait to hear the answer." -- Ed Cunningham 
<li> 'When a programming language is created that allows programmers to program in simple english, it will be discovered that programmers can not speak english'
<li> " 'Eureka' is Greek for 'This bath is too hot'. "
<li> Never argue with an idiot. They'll bring you down to their level and beat you with experience. 
<li> It is wiser to find out than to suppose. -- Mark Twain
<li> Stupidity should be painful!
<li> The only one that suffers from your hate is you, the ones you hate don't know it and the others don't care.
<li> Given enough time, and given enough money... Microsoft will eventually invent UNIX.
<li> If there is a wrong way to do something, then someone will do it. -- Edward A. Murphy Jr.
<li> Your ignorance cramps my conversation.
<li> If you understand everything on how to spend money, you should in principle understand also how to earn money, because of conservation laws...
<li> May, in spite of all distractions generated by technology, all of you succeed in turning information into knowledge, knowledge into understanding, and understanding into wisdom. - Edsger W. Dijkstra
<li> To know recursion, you must first know recursion.
</ul>

<?_foot()?>
